databases:
    name: PG-ticket-system
    databasesName: attendee
    user: attendee_user
    plan: free

services:
    type: web
    name: Rails-ticket-system
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails server"
    envVars:
        fromDatabase:
          name: mysite
          property: connectionString
        key: 8ebef870580bb390b815f11391488490
        sync:false- key: WEB_CONCURRENCY
        Value: 5